### ISSUE TITLE
Add stats

### ISSUE THREAD

**Issue by uaalto** [getlantern/http-proxy#1]
Per-server stats
- server -> num open connections
- client -> num connections

_These can't be implemented due to privacy concerns_
- client -> IP
- IP -> num connections

**Comment by uaalto** [comment]
client -> IP
client -> num connections
IP -> num connections
connection -> time alive

**Comment by fffw** [comment]
For flexibility the stats can be maintained in memory and have a command line tool or local RESTful API to query it.

**Comment by fffw** [comment]
If the only thing what we want to count are active connections and unique client IPs per server, `netstat` result should be sufficient.

**Comment by uaalto** [comment]
The idea of using Redis and actively pushing from the server to the Redis central DB is to avoid opening connections to the servers. You mean doing that by a series of scripts?

**Comment by fffw** [comment]
It can be a simple solution or workaround, but with limitations. For
example, it can't track unique  devices or users. So to me it may
sufficient for monitoring purpose, but may not enough for data our service
relies on.

**Comment by myleshorton** [comment]
Closing this bad bay.
