### ISSUE TITLE
netx error

### ISSUE THREAD

**Issue by chungnt201** [getlantern/http-proxy#103]
# github.com/getlantern/netx
..\netx\netx.go:31: undefined: context.WithTimeout
..\netx\netx.go:31: undefined: context.Background
..\netx\netx.go:39: undefined: context.Context
..\netx\netx.go:40: undefined: context.Context
..\netx\netx.go:44: undefined: context.Context
..\netx\netx.go:61: d.DialContext undefined (type net.Dialer has no field or method DialContext)
exit status 2

**Comment by joesis** [comment]
@chungnt201 please use go 1.7 or above which has the `context` package
