### ISSUE TITLE
Add proxy cache support

### ISSUE THREAD

**Issue by myleshorton** [getlantern/http-proxy#106]
This could speed things up while also reducing costs. It's effectiveness depends on the percentage of content that's HTTP and is cacheable and also on the percentage of cache hits.

Actually, this one is a strong argument for larger proxies with multiple IPs -- would drastically increase the percentage of cache hits. FYI @oxtoacart.

**Comment by myleshorton** [comment]
Note the proxy caching rules are also fairly complex and might take some time to implement correctly.

**Comment by p3rcya** [comment]
Btw, we have to be careful of the same origin proxy policy and always verify such. Otherwise, users might launch a cache poisoning scheme. I'll attach a paper that uses cache poisoning to subvert NSA website in real life.

**Comment by myleshorton** [comment]
Interesting @p3rcya

**Comment by p3rcya** [comment]
Paper is at https://www.icir.org/vern/papers/host-of-troubles.ccs16.pdf

**Comment by oxtoacart** [comment]
Using our current scheme of small proxies, we could improve cache hits by using either a centralized or distributed shared cache like [groupcache](https://github.com/golang/groupcache).
