### ISSUE TITLE
Add Device-ID in Lantern client

### ISSUE THREAD

**Issue by uaalto** [getlantern/http-proxy#2]

**Comment by fffw** [comment]
Currently we use `uuid.New()` as instance ID which changes every time, while [`uuid.NodeID()`](https://godoc.org/code.google.com/p/go-uuid/uuid#NodeID) is associated with network interface which can be considered persistent per device. We can switch to use it.

**Comment by uaalto** [comment]
Nice. That NodeID does scramble somehow the MAC address, right? So it can be uniquely associated but is not just the MAC as-is.

**Comment by uaalto** [comment]
Doesn't really matter. I've thought about it and researched the topic, and it is fine sending the NodeID. I'll open a PR with the new header field anytime soon.

**Comment by uaalto** [comment]
This would be closed by https://github.com/getlantern/lantern/pull/3310
