### ISSUE TITLE
Use token to limit the number of concurrent connections

### ISSUE THREAD

**Issue by fffw** [getlantern/http-proxy#65]
Inspired by [https://blog.golang.org/pipelines](https://blog.golang.org/pipelines#TOC_9.). It may be more clear than our current atomic + channel solution.

**Comment by fffw** [comment]
It may not work if we can't call `wg.Add` and `wg.Done` again after `wg.Wait` returns. Need some more experiments.

**Comment by fffw** [comment]
Oh I made things more complex. We can model it as a fixed set of tokens. Server doesn't `Accept` until one token available, and returns the token when connection closed.

**Comment by uaalto** [comment]
What is this for @fffw? For the connection limiter?
While I think this solution is more beautiful (but not necessarily better!), we are not even using the limiter in our proxy.

**Comment by fffw** [comment]
I just came across this and think it might be useful. Good to close it if
you think it's distracting.

**Comment by myleshorton** [comment]
Yeah I agree with @uaalto -- the connection limit to me isn't super useful since the OS itself will start to have issues if the connection limit is hit -- i.e. we might as well just make the OS the effective limiter and should scale our server as necessary in accordance with that load.

**Comment by myleshorton** [comment]
Duplicate
