### ISSUE TITLE
src/github.com/getlantern/http-proxy/forward/forward.go:178: req.URL.EscapedPath undefined

### ISSUE THREAD

**Issue by luckypoem** [getlantern/http-proxy#73]
hi.

root@AR:~/http-proxy# GOPATH=`pwd` go get -t
# github.com/getlantern/http-proxy/forward
src/github.com/getlantern/http-proxy/forward/forward.go:178: req.URL.EscapedPath undefined (type *url.URL has no field or method EscapedPath)
root@AR:~/http-proxy#

how to fix it?tks a lot

**Comment by fffw** [comment]
@luckypoem You may need Go 1.5 to have the `EscapedPath` method. Please tell us if it solves your problem so we can update README.

**Comment by luckypoem** [comment]
hi.
yes,now  it solves the problem afer i update go to 1.5
