### ISSUE TITLE
Not properly handling multiple requests over persistent connections

### ISSUE THREAD

**Issue by myleshorton** [getlantern/http-proxy#89]

**Comment by oxtoacart** [comment]
I've seen this in the past with craigslist.org (think we have a ticket but I can't find it). Today I saw it with www.roadandtrack.com and www.motortrend.com.

It's not 100% clear whether this problem is on the proxy server or in the Lantern client.

**Comment by oxtoacart** [comment]
As a test, I disabled keep alives on the local reverse proxy, and that took care of the problem. So it's very likely something related to connection closing.

**Comment by oxtoacart** [comment]
This is going to be tricky. http-proxy is just relying on the http.Transport implementation, which handles persistent connections under the covers. Unfortunately, it doesn't have a way to register a callback to detect when a persistent connection was closed, so we have no way of telling the client about it. Will do some digging, but we may need to not use http.Transport, or at least not with persistent connections enabled.

**Comment by oxtoacart** [comment]
[SCMP](http://www.scmp.com/frontpage/international) is a good example of a page that struggles under the old scheme. Where with the old version of our HTTP handling it takes the page more than 1 minute to load in Chrome (and sometimes it doesn't finish loading), under the new scheme it takes about 14 seconds.

**Comment by oxtoacart** [comment]
This is a big change, choosing to defer pulling until the next release.

**Comment by myleshorton** [comment]
This is deployed @oxtoacart correct?
