### ISSUE TITLE
Error looking up mtalk.google.com:5228

### ISSUE THREAD

**Issue by myleshorton** [getlantern/http-proxy#94]
```
Oct 30 04:01:37.367 DEBUG interceptor: interceptor.go:130 Responding BadGateway: Could not dial 'mtalk.google.com:5228': Unable to dial mtalk.google.com:5228: no suitable address found [client_ip=x.x.x.x device_id=9FyJjq3n op=proxy_https origin=mtalk.google.com:5228 root_op=proxy]
```

**Comment by uaalto** [comment]
How can I reproduce this @myleshorton? I'm assuming this is Google Talk, correct?
I've sent you a Google Talk message proxying through Lantern. @oxtoacart was able to receive a message from me.

**Comment by myleshorton** [comment]
Not sure @uaalto. I saw this that log on the server but not sure what triggered it.

**Comment by uaalto** [comment]
Ok. I will run Lantern with all Google services and search for similar logs. Was it using the latest client in lantern-pro?

**Comment by uaalto** [comment]
I'm running Lantern with `./lantern -addr=:8787 2>&1 | grep mtalk` and nothing shows up for now. I'll keep trying to reproduce.
One strange behavior I get though is that sometimes I can't login at first try in Google Talk, but as soon as I retry it works immediately. No related output I could find though.

**Comment by uaalto** [comment]
I can't reproduce after continuously using Lantern for 2 days and trying with Google Talk in FF and Chromium.

**Comment by oxtoacart** [comment]
Sounds like it was maybe a transient DNS issue. I took a look at one of our busier Google proxy servers and out of 99k log lines, "no suitable address found" shows up a total of 20 times, all clustered at exactly the same time.

I say we close.
